### ISSUE TITLE
Some feedbacks

### ISSUE THREAD

**Issue by ghost** [crysalead-js/lead-ui#1]
Hi. I saw you released your ui library, and I was looking into the code. First I have to say, it's obvious a lot of work to do. Anyway.  Here are a few things.
1. You are in deep trouble if you plan to use this library with Chrome Extensions.  I say so because of your use of `Function`. Most of the time you will get this error message if you try:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:"
```

So to get this working, you need to remain your users to create a sandbox. https://developer.chrome.com/extensions/sandboxingEval
1. Why 2 different event systems? I thought you had one already that worked for domLayer?
2. Use of bind() are terrible slow, and can and should be avoided. You are not using it one place, but a whole bunch of different places.

http://stackoverflow.com/questions/18895305/will-function-prototype-bind-always-be-slow
http://stackoverflow.com/questions/17638305/why-is-bind-slower-than-a-closure

I know you want things in separate issues, but I just compressed it now to give a few feedbacks.

**Comment by jails** [comment]
Yup it's mostly a draft right now but the examples works.
1. I'm not sure to get all this "CSP" thingy but it's not a big deal. I moved this up to building script.
2. There's no 2 different event systems. The transpiler just collect the `onxxxx` references from the html template to build a valid `events` object entry for the `dom-layer`. When events are catched by `dom-layer` the callbacks are executed which generaly run a component scope method.
3. Unless you're creating an application where .bind() is called so many times that it become a bottleneck I wouldn't bother. Readability is much more important than sheer performance imo. A lot of notable developpers avoid the `var self = this` pattern when it doesn't lead to performance issue.
